apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: birthday-bot-role
  namespace: birthday-bot
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
