apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: birthday-bot
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: UkVQTEFDRV9NRV9URUxFR1JBTV9UT0tFTg==
  TELEGRAM_WEBHOOK_SECRET: UkVQTEFDRV9NRV9XRUJIT09LX1NFQ1JFVA==
  MONGODB_URI: bW9uZ29kYjovL3VzZXI6cGFzc0Btb25nb2RiOjI3MDE3L2JpcnRoZGF5cz9yZXBsaWNhU2V0PXJzMA==
  ASPNETCORE_ENVIRONMENT: UHJvZHVjdGlvbg==
  TZ: RXVyb3BlL1dhcnNhdw==
