apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotTokenB64 | quote }}
  TELEGRAM_WEBHOOK_SECRET: {{ .Values.secrets.telegramWebhookSecretB64 | quote }}
  MONGODB_URI: {{ .Values.secrets.mongodbUriB64 | quote }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.secrets.aspnetcoreEnvB64 | quote }}
  TZ: {{ .Values.secrets.tzB64 | quote }}
