apiVersion: v1
kind: Service
metadata:
  name: birthday-bot-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: birthday-bot-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
