apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
